{"level":"error","message":"Erro capturado em triggerError","timestamp":"2024-10-09T23:51:20.128Z","trace":"Error: Erro intencional para teste do Sentry\n    at AppService.triggerError (/app.service.ts:24:13)\n    at AppController.getError (/app.controller.ts:15:28)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at bound (node:async_hooks:238:16)\n    at Observable._subscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable.Observable._trySubscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n    at <anonymous> (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18)"}
{"level":"error","message":"Erro capturado em triggerError","timestamp":"2024-10-09T23:52:00.363Z","trace":"Error: Erro intencional para teste do Sentry\n    at AppService.triggerError (/app.service.ts:24:13)\n    at AppController.getError (/app.controller.ts:15:28)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at bound (node:async_hooks:238:16)\n    at Observable._subscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable.Observable._trySubscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n    at <anonymous> (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18)"}
{"level":"error","message":"Erro capturado em triggerError","timestamp":"2024-10-09T23:52:01.167Z","trace":"Error: Erro intencional para teste do Sentry\n    at AppService.triggerError (/app.service.ts:24:13)\n    at AppController.getError (/app.controller.ts:15:28)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at bound (node:async_hooks:238:16)\n    at Observable._subscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable.Observable._trySubscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n    at <anonymous> (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18)"}
{"level":"error","message":"Erro capturado em triggerError","timestamp":"2024-10-09T23:52:01.510Z","trace":"Error: Erro intencional para teste do Sentry\n    at AppService.triggerError (/app.service.ts:24:13)\n    at AppController.getError (/app.controller.ts:15:28)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at bound (node:async_hooks:238:16)\n    at Observable._subscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable.Observable._trySubscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n    at <anonymous> (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18)"}
{"level":"error","message":"Erro capturado em triggerError","timestamp":"2024-10-09T23:52:01.803Z","trace":"Error: Erro intencional para teste do Sentry\n    at AppService.triggerError (/app.service.ts:24:13)\n    at AppController.getError (/app.controller.ts:15:28)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_@nestjs+platform-express@10.4.4_reflect-metadata@0.2.2_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at bound (node:async_hooks:238:16)\n    at Observable._subscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable.Observable._trySubscribe (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n    at <anonymous> (/Users/rafaelnery/Documents/GitHub/nodejs_sr_spec_test_1/parte2/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18)"}
{"level":"error","message":"Usuário com ID invalidid não encontrado","timestamp":"2024-10-09T23:58:58.964Z","trace":"UserService"}
{"level":"error","message":"Usuário com ID invalidid não encontrado","timestamp":"2024-10-09T23:58:58.983Z","trace":"UserService"}
